package models
package models

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID `json:"id"`





















































































































}	PartnerSignedPreKey *string `json:"partner_signed_prekey,omitempty"`	PartnerEphemeralKey *string `json:"partner_ephemeral_key,omitempty"`	PartnerAnonymousID *uuid.UUID `json:"partner_anonymous_id,omitempty"`	MatchID      *uuid.UUID `json:"match_id,omitempty"`	Matched      bool      `json:"matched"`type MatchStatusResponse struct {}	EphemeralSignedPreKey string   `json:"ephemeral_signed_prekey"`	EphemeralIdentityKey  string   `json:"ephemeral_identity_key"`	CategoryTags          []string `json:"category_tags"`type JoinMatchQueueRequest struct {}	OneTimePreKeys []PreKey `json:"onetime_prekeys"`	SignedPreKey   PreKey   `json:"signed_prekey"`	DeviceID       string   `json:"device_id"`type UploadPreKeysRequest struct {}	RegistrationID   int       `json:"registration_id"`	OneTimePreKey    *PreKey   `json:"onetime_prekey,omitempty"`	SignedPreKey     PreKey    `json:"signed_prekey"`	IdentityKey      string    `json:"identity_key"`	DeviceID         string    `json:"device_id"`	UserID           uuid.UUID `json:"user_id"`type PreKeyBundle struct {}	ExpiresAt time.Time `json:"expires_at"`	UserID uuid.UUID `json:"user_id"`	Token  string    `json:"token"`type LoginResponse struct {}	DeviceID string  `json:"device_id"`	Password string  `json:"password"`	Phone    *string `json:"phone,omitempty"`	Email    *string `json:"email,omitempty"`type LoginRequest struct {}	Code  string  `json:"code"`	Phone *string `json:"phone,omitempty"`	Email *string `json:"email,omitempty"`type VerifyRequest struct {}	RegistrationID int  `json:"registration_id"`	DeviceID    string  `json:"device_id"`	IdentityKey string  `json:"identity_key"`	Password    string  `json:"password"`	Phone       *string `json:"phone,omitempty"`	Email       *string `json:"email,omitempty"`type RegisterRequest struct {// Request/Response models}	EndedAt      *time.Time `json:"ended_at,omitempty"`	MatchedAt    time.Time  `json:"matched_at"`	Anonymous2ID uuid.UUID  `json:"anonymous2_id"`	Anonymous1ID uuid.UUID  `json:"anonymous1_id"`	User2ID      *uuid.UUID `json:"user2_id,omitempty"`	User1ID      *uuid.UUID `json:"user1_id,omitempty"`	ID           uuid.UUID  `json:"id"`type ActiveMatch struct {}	JoinedAt              time.Time `json:"joined_at"`	EphemeralSignedPreKey string    `json:"ephemeral_signed_prekey"`	EphemeralIdentityKey  string    `json:"ephemeral_identity_key"`	CategoryTags          []string  `json:"category_tags"`	AnonymousID           uuid.UUID `json:"anonymous_id"`	UserID                *uuid.UUID `json:"user_id,omitempty"`	ID                    uuid.UUID `json:"id"`type MatchQueueEntry struct {}	CreatedAt    time.Time `json:"created_at"`	ExpiresAt    time.Time `json:"expires_at"`	SessionToken string    `json:"session_token"`	UserID       uuid.UUID `json:"user_id"`	ID           uuid.UUID `json:"id"`type Session struct {}	CreatedAt  time.Time `json:"created_at"`	IsUsed     bool      `json:"is_used"`	IsSigned   bool      `json:"is_signed"`	Signature  *string   `json:"signature,omitempty"`	PublicKey  string    `json:"public_key"`	KeyID      int       `json:"key_id"`	DeviceID   string    `json:"device_id"`	UserID     uuid.UUID `json:"user_id"`	ID         int       `json:"id"`type PreKey struct {}	LastSeen       time.Time `json:"last_seen"`	CreatedAt      time.Time `json:"created_at"`	RegistrationID int       `json:"registration_id"`	DeviceID       string    `json:"device_id"`	UserID         uuid.UUID `json:"user_id"`	ID             uuid.UUID `json:"id"`type Device struct {}	UpdatedAt     time.Time `json:"updated_at"`	CreatedAt     time.Time `json:"created_at"`	TwoFASecret   string    `json:"-"`	TwoFAEnabled  bool      `json:"two_fa_enabled"`	IdentityKey   string    `json:"identity_key"`	PasswordHash  string    `json:"-"`	Phone         *string   `json:"phone,omitempty"`	Email         *string   `json:"email,omitempty"`