package db
package db




















































































































}	return err	_, err := db.conn.Exec(schema)	`	);		ended_at TIMESTAMP		matched_at TIMESTAMP DEFAULT NOW(),		anonymous2_id UUID NOT NULL,		anonymous1_id UUID NOT NULL,		user2_id UUID,		user1_id UUID,		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	CREATE TABLE IF NOT EXISTS active_matches (	CREATE INDEX IF NOT EXISTS idx_match_queue_tags ON match_queue USING GIN(category_tags);	);		joined_at TIMESTAMP DEFAULT NOW()		ephemeral_signed_prekey TEXT NOT NULL,		ephemeral_identity_key TEXT NOT NULL,		category_tags TEXT[] NOT NULL,		anonymous_id UUID NOT NULL,		user_id UUID REFERENCES users(id) ON DELETE CASCADE,		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	CREATE TABLE IF NOT EXISTS match_queue (	CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(session_token);	);		created_at TIMESTAMP DEFAULT NOW()		expires_at TIMESTAMP NOT NULL,		session_token TEXT NOT NULL UNIQUE,		user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	CREATE TABLE IF NOT EXISTS sessions (	CREATE INDEX IF NOT EXISTS idx_prekeys_unused ON prekeys(user_id, device_id, is_used) WHERE is_used = FALSE;	CREATE INDEX IF NOT EXISTS idx_prekeys_user_device ON prekeys(user_id, device_id);	);		UNIQUE(user_id, device_id, key_id)		created_at TIMESTAMP DEFAULT NOW(),		is_used BOOLEAN DEFAULT FALSE,		is_signed BOOLEAN DEFAULT FALSE,		signature TEXT,		public_key TEXT NOT NULL,		key_id INTEGER NOT NULL,		device_id VARCHAR(255) NOT NULL,		user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,		id SERIAL PRIMARY KEY,	CREATE TABLE IF NOT EXISTS prekeys (	);		UNIQUE(user_id, device_id)		last_seen TIMESTAMP DEFAULT NOW(),		created_at TIMESTAMP DEFAULT NOW(),		registration_id INTEGER NOT NULL,		device_id VARCHAR(255) NOT NULL,		user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	CREATE TABLE IF NOT EXISTS devices (	);		CHECK (email IS NOT NULL OR phone IS NOT NULL)		updated_at TIMESTAMP DEFAULT NOW(),		created_at TIMESTAMP DEFAULT NOW(),		two_fa_secret TEXT,		two_fa_enabled BOOLEAN DEFAULT TRUE,		identity_key TEXT NOT NULL,		password_hash TEXT NOT NULL,		phone VARCHAR(20) UNIQUE,		email VARCHAR(255) UNIQUE,		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	CREATE TABLE IF NOT EXISTS users (	schema := `func (db *DB) Migrate() error {}	return db.connfunc (db *DB) Conn() *sql.DB {}	return db.conn.Close()func (db *DB) Close() error {}	return &DB{conn: conn}, nil	}		return nil, fmt.Errorf("failed to ping database: %w", err)	if err := conn.Ping(); err != nil {	}		return nil, fmt.Errorf("failed to open database: %w", err)	if err != nil {	conn, err := sql.Open("postgres", dbURL)	}		return nil, fmt.Errorf("DATABASE_URL environment variable is not set")	if dbURL == "" {	dbURL := os.Getenv("DATABASE_URL")func NewDB() (*DB, error) {}	conn *sql.DBtype DB struct {)	_ "github.com/lib/pq"	"os"	"fmt"	"database/sql"import (